### ISSUE TITLE
integration in git of the "Drones: escaping from a labyrinth" exercise

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot-TeachingRobotics#10]
Second practical exercise at the "advanced programming drones" course. It was developed by @edupergar  and it would be great to have it integrated in this git repo.

The demo video can be found at http://jderobot.org/Programacion-avanzada-de-drones#Pr.C3.A1ctica_2:_Escapando_de_un_laberinto_con_flechas_de_ayuda

**Comment by eperdices** [comment]
Uploaded exercise code and gazebo resources
