### ISSUE TITLE
integration in git of the "Drones: rescuing people" exercise

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot-TeachingRobotics#11]
Third practical exercise at the "advanced programming drones" course. It was developed by @eperdices and it would be great to have it integrated in this git repo.

The demo video can be found at http://jderobot.org/Programacion-avanzada-de-drones#Pr.C3.A1ctica_3:_B.C3.BAsqueda_de_personas_tras_una_cat.C3.A1strofe

**Comment by eperdices** [comment]
Uploaded exercise code and gazebo resources
