### ISSUE TITLE
new exercise: 3D reconstruction from stereo pair

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot-TeachingRobotics#2]
Development of the academic components for this exercise. The demo video can be found at 
http://jderobot.org/Teaching_robotics_with_JdeRobot#Visual_3D_reconstruction_from_a_stereo_pair_of_RGB_cameras

In Python and using OpenCV.

**Comment by chanfr** [comment]
First step is to change progeo from c++ to python.

**Comment by chanfr** [comment]
Completed!
