### ISSUE TITLE
new exercise: Formula1, visual follow line

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot-TeachingRobotics#3]
Development of new academic component for this exercise. In Python and using OpenCV. The demo video can be found at http://jderobot.org/Teaching_robotics_with_JdeRobot#Visual_follow-line_behavior

**Comment by chanfr** [comment]
First version is now available in the repository but we are waiting to finish the F1 world -> #31

**Comment by fqez** [comment]
Yeah, sorry. I will have it ready most likely tomorrow. I let you know by then.

**Comment by chanfr** [comment]
Included F1 support for follow_line component
