### ISSUE TITLE
new exercise: obstacle avoidance

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot-TeachingRobotics#30]
VFF algorithm for local navigation. Target positions from file and from a local GUI, with 1m2 squares

**Comment by eperdices** [comment]
Our VFF implementation uses two forces, attraction force and repulsive force:
- Attraction force is calculated regarding the distance between the target and current robot's position.
- Repulsive force is calculated taking into account each laser measure, ignoring obstacles located far enough from the robot.
Both forces are decomposed into two coordinates (x-y) and added to calculate the resultant force. This resultant force will be used to set robot's movement.
