### ISSUE TITLE
scenario for global navigation exercise

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot-TeachingRobotics#35]
The infrastructure needed is composed of a car model, a small city in Gazebo, and a png map of such city. 

The car model (taxi) will be included in JdeRobot repository, so it can be used in general. The Gazebo world file will include the town in 3D. The town map in png will be provided to the application software to use it for path planning.

**Comment by reysam93** [comment]
The world and the map of the city have been added in the teleTaxi folder. Also the models, as I haven't made the pull request to JdeRobot yet.

**Comment by fqez** [comment]
Hi, 
it's ok by now, but when the models are in the official repo could you please remove them from the exercise? This way we have all the models located in one directory (/usr/local/share/jderobot/gazebo/models) and here we have only the worlds that use them. Good job!!

**Comment by reysam93** [comment]
No problem, I have already remove it from this repository and the are in the JdeRobot repository, with the other models of gazeboserver.
