### ISSUE TITLE
Create new gazebo world with obstacles inside a circuit

### ISSUE THREAD

**Issue by eperdices** [RoboticsURJC/JdeRobot-TeachingRobotics#39]
Create a new gazebo world similar to "simpleCircuit.world" including obstacles (vehicles). This world will be used to test a VFF algorithm.

**Comment by fqez** [comment]
I'm goint to add the simpleCircuitObstacles.world from the JdeRobot official repo. Could you tell me please in which example you want the world?
Thanks!

**Comment by eperdices** [comment]
I am creating a new exercise called obstacle avoidance to implement a VFF algorithm, but I haven't uploaded it yet.

I have seen that you have already uploaded to JdeRobot a new world with obstacles, I will try to use that one and I will tell you if it works fine.

**Comment by eperdices** [comment]
The new world works ok and has enough cars to test the algorithm, so I close this issue.
Thanks!
