### ISSUE TITLE
Fake walls in simpleCircuit.world

### ISSUE THREAD

**Issue by eperdices** [RoboticsURJC/JdeRobot-TeachingRobotics#40]
As you can see on the picture there are two wall at both sides of F1 car, left wall is detected correctly with laser but right wall is "transparent" to laser measures. The same happens if I try to crash the car into the walls, left wall works well but the car is able to go through the right wall as if it didn't exist.

![laser](https://cloud.githubusercontent.com/assets/15780113/13843974/2ffae1ca-ec37-11e5-939c-b3beb7a21668.png)

**Comment by fqez** [comment]
Hi, yes the collision for that walls were not modeled. I didn't think it was necessary, but if you need I can add them to.

**Comment by fqez** [comment]
Should be solved here: https://github.com/RoboticsURJC/JdeRobot/pull/395

**Comment by eperdices** [comment]
Works perfect, thank you!
