### ISSUE TITLE
integration in git of the "Vision, color filter" exercise

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot-TeachingRobotics#5]
First practical exercise at the "basic programming drones" course. It was developed by @almartinflorido and it would be great to have it integrated in this git repo
The demo video is http://jderobot.org/Programacion-de-drones#Pr.C3.A1ctica_filtros_de_color

**Comment by almartinflorido** [comment]
@jmplaza  the color_filter component has been added.

Now to extract the values of HSV filter is necessary execute colorTurner component to establish this values in color_filter component.
