### ISSUE TITLE
integration in git of the "Position based navigation for drones" exercise

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot-TeachingRobotics#6]
Second practical exercise at the "basic programming drones" course. It was developed by @almartinflorido and it would be great to have it integrated in this git repo
The demo video can be found at http://jderobot.org/Programacion-de-drones#Pr.C3.A1ctica_control_en_posici.C3.B3n_con_PID

**Comment by almartinflorido** [comment]
@jmplaza the position_control component has been added.
