### ISSUE TITLE
integration in git of the "Drones: follow the turtle in the ground" exercise

### ISSUE THREAD

**Issue by jmplaza** [RoboticsURJC/JdeRobot-TeachingRobotics#7]
Third practical exercise at the "basic programming drones" course. It was developed by @almartinflorido and it would be great to have it integrated in this git repo
The demo video can be found at http://jderobot.org/Programacion-de-drones#Pr.C3.A1ctica_Atrapa_a_la_tortuga

**Comment by almartinflorido** [comment]
@jmplaza added catch_turtle component
